# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2023-11-06 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20231106_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App_tasks',
            new_name='Tasks',
        ),
    ]
